apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-webhook-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Release.Name }}-webhook-ca
  secretName: {{ .Release.Name }}-webhook-ca
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Release.Name }}-webhook-ca
