from . import deployment
from . import filestore_pvc
from . import git_repo_pvc
from . import ingress_routes
from . import odoo_conf
from . import odoo_handler
from . import odoo_user_secret
from . import pull_secret
from . import pvc_handler
from . import resource_handler
from . import service
from . import tls_cert
